#######################################################
# This file configures builders running sequence and  #
# paths that they should check and generate files for #
#######################################################
targets:
  drift:
    auto_apply_builders: false
    builders:
      drift_dev:analyzer:
        enabled: true
        options: &options
          # Drift build options, as per https://drift.simonbinder.eu/docs/advanced-features/builder_options/
          store_date_time_values_as_text: true
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.39"
              modules: [ fts5 ]
      drift_dev:modular:
        enabled: true
        # We use yaml anchors to give the two builders the same options
        options: *options
  $default:
    dependencies:
      - ":drift"
    builders:
      drift_dev:
        enabled: false
      source_gen|combining_builder:
        options:
          errors:
            - invalid_annotation_target
      freezed:
        enabled: true
        options:
          generic_argument_factories: true
        generate_for:
          include:
            - lib/features/**/*.dart
            - lib/domain/usecases/params/**/*.dart
            - lib/data/dto/**/*.dart
            - lib/data/models/**/*.dart
            - lib/domain/**/*.dart
            - lib/data/params/**/*.dart
            - lib/data/request/**/*.dart
            - lib/data/response/**/*.dart
            - lib/data/state/**/*.dart
            - lib/data/store/**/*.dart
            - lib/router/**/*.dart
      json_serializable:
        enabled: true
        generate_for:
          include:
            - test/**/*.dart
            - lib/features/**/*.dart
            - lib/data/dto/**/*.dart
            - lib/data/models/**/*.dart
            - lib/domain/**/*.dart
            - lib/data/params/**/*.dart
            - lib/data/request/**/*.dart
            - lib/data/response/**/*.dart
            - lib/data/state/**/*.dart
            - lib/data/store/**/*.dart
            - lib/router/**/*.dart
      retrofit_generator:
        enabled: true
        generate_for:
          include:
            - lib/data/services/**/*.dart
      go_router_builder:
        enabled: true
        generate_for:
          include:
            - lib/router/**/*.dart
      injectable_generator|injectable_config_builder:
        enabled: true
      mockito|mockBuilder:
        enabled: true
        generate_for:
          include:
            - test/**/*.dart

global_options:
  drift_dev:modular:
    runs_before:
      - mockito|mockBuilder
      - freezed
      - json_serializable
  freezed:
    runs_before:
      - mockito|mockBuilder
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
      - mockito|mockBuilder
  retrofit_generator:
    runs_before:
      - mockito|mockBuilder
  injectable_generator|injectable_config_builder:
    runs_before:
      - freezed
      - json_serializable
      - mockito|mockBuilder
  go_router_builder:
    runs_before:
      - freezed
      - json_serializable
      - mockito|mockBuilder
      - injectable_generator|injectable_config_builder